### ISSUE TITLE
Moodle Hammer Time

### ISSUE THREAD

**Issue by halbtuerke** [manly-man/moodle-destroyer-tools#1]
I want it please!! NOW!!

**Comment by deubzerm** [comment]
can't remember what the hammer is supposed to smash ?

**Comment by halbtuerke** [comment]
It should hammer the broken CSV into proper shape.

**Comment by halbtuerke** [comment]
PING!

**Comment by deubzerm** [comment]
PONG!

2015-02-11 15:14 GMT+01:00 Patrick notifications@github.com:
