### ISSUE TITLE
[devel]  extractor uses folders in cwd instead of groups for grading file entries

### ISSUE THREAD

**Issue by einsweniger** [manly-man/moodle-destroyer-tools#7]
Des sind so grob die Ordner und Dateien im Ordner in dem extractor ausgeführt wird. 
I blame onc :D

gradingfile.csv:
Gruppe,Bewertung,Feedback als Kommentar
Bewertungen,,
CS3100.010,,
alt,,
gdra,,

**Comment by halbtuerke** [comment]
I don't understand the issue.

What is it that you are expecting and what is the actual outcome?

**Comment by einsweniger** [comment]
Gewollt sind in der Gradingfile die einzelnen Gruppen untereinander. Bekommen tu ich ne gradingfile die Ordner und files aus dem current Wirkung dir enthält.
Sorry für den schlampigen Bug, hab grad Zeitdruck :/

**Comment by einsweniger** [comment]
Achso: im master geht's noch. Ist nur auf der develop branch

**Comment by halbtuerke** [comment]
It seems you broke something in develop @onc.

**Comment by onc** [comment]
i'm not sure if i got this... but i look into it later.

p.s. works for me
p.p.s. its not a bug, its a feature
